#!/bin/bash
#PBS -P v10
#PBS -q normal
#PBS -l walltime=01:00:00,ncpus=1,mem=12940MB
#PBS -l wd
#PBS -me

module use /projects/u46/opt/modules/modulefiles
module load python/2.7.6
module load hdf4/4.2.6
module load gdal
module load proj
module load IDL_functions
module load pyephem
module load numexpr
module load scikit-image

export IMAGEPROCESSOR_ROOT=$(readlink -f ${0%/*}/..)
export L1T_ROOT=/g/data/v10/NBAR_validation_reference/Nov2013/L1T_Input/LS7_90-84_2013-10-03/UTM/LS7_ETM_OTH_P51_GALPGS01-002_090_084_20131003
export OUTPUT_ROOT=/short/v10/${USER}/tc
export VALID_ROOT=${OUTPUT_ROOT}_mock

PYTHONPATH=$PYTHONPATH:$IMAGEPROCESSOR_ROOT

echo OUTPUT_ROOT: ${OUTPUT_ROOT}
echo VALID_ROOT: ${VALID_ROOT}

if [ ! -d "${VALID_ROOT}" ]; then 
	echo "Performing a first run to save valid outputs at" `date`

	echo "Creating the output directories"
	mkdir -p ${VALID_ROOT}/work
	mkdir -p ${VALID_ROOT}/output

	# save so we can come back easily later
	pushd `pwd`

	echo "Removing previous binaries"
	rm ../bin/*

	echo "Compiling fortran codes"
	cd ../fortran
	make install

	echo "Compiling C codes"
	cd ../src
	make install

	popd

	../process.py --sequential --debug --work ${VALID_ROOT}/work --process_level tc --nbar-root ${VALID_ROOT}/output --l1t ${L1T_ROOT}

	echo "Finished run at" `date`
else
	echo "Performing a mock"

	echo "Creating the output directories"
	rm -fr ${OUTPUT_ROOT}/work
	rm -fr ${OUTPUT_ROOT}/output
	mkdir -p ${OUTPUT_ROOT}/work
	mkdir -p ${OUTPUT_ROOT}/output

	echo "Replacing Fortran code by mock version"
	cp ../fortran/mock/* ../bin

	echo "Starting mocked run at" `date` 

	../process.py --sequential --debug --work ${OUTPUT_ROOT}/work --process_level tc --nbar-root ${OUTPUT_ROOT}/output --l1t ${L1T_ROOT}

	echo "Finished run at" `date`
fi

