#!/bin/bash
#PBS -P v10
#PBS -q normal
#PBS -l walltime=00:30:00,ncpus=1,mem=6GB
#PBS -l wd
#PBS -me
#PBS -M Alex.Ip@ga.gov.au
#####PBS -joe -o runfrac_landsat_v3.olog

module load python/2.7.3
module load hdf4/4.2.6
module load gdal
module load proj

module use /g/data/v10/opt/modules/modulefiles --append
module load IDL_functions
module load pyephem
module load numexpr


export IMAGEPROCESSOR_ROOT=$(readlink -f ${0%/*}/..)
export FC_ROOT=$IMAGEPROCESSOR_ROOT/image_processor/fc
export PATH=$FC_ROOT:$PATH

export OUTPUT_ROOT=/short/v10/tmp/${USER}/ula3_tests/fc
mkdir -p ${OUTPUT_ROOT}/work
mkdir -p ${OUTPUT_ROOT}/output

../process.py --sequential --debug --work ${OUTPUT_ROOT}/work --process_level fc --fc ${OUTPUT_ROOT}/output --nbar /g/data/v10/NBAR/2009-01/LS5_TM_NBAR_P54_GANBAR01-002_092_086_20090115

