#!/bin/bash
#PBS -P v10
#PBS -q express
#PBS -l walltime=00:30:00,ncpus=1,mem=6GB
#PBS -l wd
#PBS -me
##PBS -M 

module load python/2.7.3
module use /projects/u46/opt/modules/modulefiles --append
module load image_processor

export OUTPUT_ROOT=/short/v10/$USER/FC_testing
mkdir -p ${OUTPUT_ROOT}/work
mkdir -p ${OUTPUT_ROOT}/output

process.py --sequential --debug --work ${OUTPUT_ROOT}/work --process_level fc --fc ${OUTPUT_ROOT}/output --nbar /g/data1/rs0/scenes/ARG25_V0.0/2009-01/LS5_TM_NBAR_P54_GANBAR01-002_092_086_20090115

