#!/bin/bash
#PBS -P v10
#PBS -q express
#PBS -l walltime=00:30:00,ncpus=1,mem=6GB
#PBS -l wd
#PBS -me
##PBS -M 

module load python/2.7.6
module load gcc/4.9.0
module use /projects/u46/opt/modules/modulefiles
module load luigi-mpi
module load mpi4py/20141106
module load rasterio
module load EOtools
module load IDL_functions
module load scikit-image


export OUTPUT_ROOT=/short/v10/$USER/FC_luigi_testing
rm -r ${OUTPUT_ROOT}
mkdir -p ${OUTPUT_ROOT}/work
mkdir -p ${OUTPUT_ROOT}/output
mkdir -p ${OUTPUT_ROOT}/logs


# override the image_processor so we get out code
export PYTHONPATH=/home/547/smr547/ga-neo-landsat-processor:$PYTHONPATH

python ./fc.py FractionalCoverTask --local-scheduler \
--nbar-path /g/data1/rs0/scenes/ARG25_V0.0/2009-01/LS5_TM_NBAR_P54_GANBAR01-002_092_086_20090115 \
--fc-path ${OUTPUT_ROOT}/output/LS5_TM_NBAR_P54_GAFC01-002_092_086_20090115
