#!/bin/bash
#PBS -P v10
#PBS -q express
#PBS -l walltime=00:30:00,ncpus=1,mem=6GB
#PBS -l wd
#PBS -me
##PBS -M 

module load python/2.7.3
module use /projects/u46/opt/modules/modulefiles --append
module load luigi
module load image_processor
module load EOtools

export OUTPUT_ROOT=/short/v10/$USER/FC_luigi_testing
rm -r ${OUTPUT_ROOT}
mkdir -p ${OUTPUT_ROOT}/work
mkdir -p ${OUTPUT_ROOT}/output


python ./fc.py FractionalCoverTask --local-scheduler \
--nbar-path /g/data1/rs0/scenes/ARG25_V0.0/2009-01/LS5_TM_NBAR_P54_GANBAR01-002_092_086_20090115 \
--fc-path ${OUTPUT_ROOT}/output/LS5_TM_NBAR_P54_GAFC01-002_092_086_20090115
