#!/bin/bash
#PBS -P v10
#PBS -q express
#PBS -l walltime=00:30:00,ncpus=32,mem=63GB
#PBS -l wd
#PBS -me
##PBS -M 

module load python/2.7.6
module use /projects/u46/opt/modules/modulefiles --append
module load image_processor
module load EOtools
module load openmpi/1.8
module load pypar


export OUTPUT_ROOT=/short/v10/$USER/FC_luigi_mpi_testing
rm -r ${OUTPUT_ROOT}
mkdir -p ${OUTPUT_ROOT}/work
mkdir -p ${OUTPUT_ROOT}/output

# process.py --sequential --debug --work ${OUTPUT_ROOT}/work --process_level fc \
# --fc ${OUTPUT_ROOT}/output \
# --nbar /g/data1/rs0/scenes/ARG25_V0.0/2009-01/LS5_TM_NBAR_P54_GANBAR01-002_092_086_20090115


export PYTHONPATH=/home/547/smr547/luigi:$PYTHONPATH

mpirun -n 32 python ./Test_FC_mpi.py 
