#!/bin/bash
# useage: 
#    qsub -v L1T_PATH=...,NBAR_PATH=... test_old_pq.pbs
#--------------------------------

#PBS -P v10
#PBS -q normal
#PBS -l walltime=00:20:00,ncpus=1,mem=12940MB
#PBS -l wd
#PBS -me
##PBS -M joshua.sixsmith@ga.gov.au
## Change the above email address and remove the first # symbol


echo "L1T_PATH=$L1T_PATH"
echoerr() { echo "$@" 1>&2; }

# CHECK PARAMS
# ============
if [[ -z "$L1T_PATH" ]]; then
   echoerr L1T_PATH not defined
   exit 1
fi
if [[ -z "$NBAR_PATH" ]]; then
   echoerr NBAR_PATH not defined
   exit 1
fi


echo 'y' | module clear
module load python/2.7.6
module load hdf4/4.2.6
module load gdal
module load proj

module use /projects/u46/opt/modules/modulefiles
module load image_processor
#module load numexpr
#module load IDL_functions
#module load pyephem


export IMAGEPROCESSOR_ROOT=$(readlink -f ${0%/*}/..)
export OUTPUT_ROOT=/short/v10/${USER}/pqa

WORK_PATH=${OUTPUT_ROOT}/work_${HOSTNAME}_$$
#WORK_PATH=${PBS_JOBFS}
mkdir -p $WORK_PATH
mkdir -p ${OUTPUT_ROOT}/output

process.py --sequential --work $WORK_PATH --process_level pqa --pqa-root ${OUTPUT_ROOT}/output \
 --l1t $L1T_PATH \
 --nbar $NBAR_PATH \
 --debug

