#!/bin/bash
#PBS -P v10
#PBS -q normal
#PBS -l walltime=05:30:00,ncpus=64,mem=128GB,jobfs=4GB
#PBS -l wd
#PBS -me
##PBS -M 

module load python/2.7.6
module load gcc/4.9.0
module use /projects/u46/opt/modules/modulefiles 
module load luigi-mpi
module load mpi4py/20141106
module load rasterio
module load EOtools
module load IDL_functions
module load scikit-image

cat $PBS_NODEFILE

export OUTPUT_ROOT=/short/v10/$USER/FC_luigi_mpi_testing
rm -r ${OUTPUT_ROOT}
mkdir -p ${OUTPUT_ROOT}/work
mkdir -p ${OUTPUT_ROOT}/output
mkdir -p ${OUTPUT_ROOT}/logs

# override the image_processor so we get out code
export PYTHONPATH=/home/547/smr547/ga-neo-landsat-processor:$PYTHONPATH

# now run on all nodes
mpirun -npernode 8 python ./fc.py  \
--nbar_path ../gaip/tests/data/NBAR/2014-12 \
--out_path ${OUTPUT_ROOT}/output \
--log_path ${OUTPUT_ROOT}/logs
